"""
Curated photo manifest for honeycombint.com.

Each entry: (source path relative to the archive folder, output slug, group, caption)
Groups: process | craft | archive | people | catalogue
"""

W = "Workshop_Sample Development"
C = "Collection Old Textiles_Jewellery/TEXTILE"
H = "HCI/website"

PHOTOS = [
    # ---------- Hand quilting / kantha stitching ----------
    (f"{W}/DSC00162.JPG", "quilting-01", "process", "Hand-quilting a cotton bedcover, stitch by stitch"),
    (f"{W}/DSC00172.JPG", "quilting-02", "process", "Running stitch through layers of soft cotton"),
    (f"{W}/DSC00173.JPG", "quilting-03", "process", "An artisan hand-quilting in the workshop"),
    (f"{W}/DSC00170.JPG", "quilting-hands", "process", "The needle and the thread, close up"),
    (f"{W}/DSC00395.JPG", "village-quilting-01", "people", "Village women hand-quilting block-printed cloth"),
    (f"{W}/DSC00398.JPG", "village-quilting-02", "people", "A circle of quilters at work"),
    (f"{W}/DSC00401.JPG", "village-quilting-03", "people", "Quilting under the open sky"),
    (f"{W}/DSC00402.JPG", "village-quilting-04", "people", "Hand-quilting a block-printed quilt"),
    (f"{W}/DSC00409.JPG", "village-quilting-05", "people", "Quilting by hand"),
    (f"{W}/DSC00418.JPG", "village-quilting-06", "process", "Bangled hands over hand-stitched cloth"),
    (f"{W}/DSC00419.JPG", "village-quilting-07", "people", "Every quilt is finished by hand"),
    (f"{W}/DSC00447.JPG", "village-hut", "people", "A mud-and-thatch home where quilters work"),
    # ---------- Applique / patchwork ----------
    (f"{W}/DSC00181.JPG", "applique-cut-01", "process", "Cutting appliqué motifs with heavy iron shears"),
    (f"{W}/DSC00184.JPG", "applique-cut-02", "process", "Freehand cutting, no template"),
    (f"{W}/DSC00186.JPG", "applique-cut-03", "process", "Cutting the appliqué"),
    (f"{W}/DSC00188.JPG", "applique-lay-01", "process", "Laying out cut-work before stitching"),
    (f"{W}/DSC00190.JPG", "applique-lay-02", "process", "Placing appliqué pieces on the ground cloth"),
    (f"{W}/DSC00200.JPG", "spiral-01", "process", "Hand-stitching a spiral appliqué"),
    (f"{W}/DSC00202.JPG", "spiral-02", "process", "Spiral appliqué in progress"),
    (f"{W}/DSC00203.JPG", "spiral-03", "process", "The spiral takes shape"),
    (f"{W}/DSC00225.JPG", "sample-spiral", "craft", "Finished spiral appliqué cushion sample"),
    (f"{W}/DSC00218.JPG", "sample-circles", "craft", "Quilted circles, sample development"),
    (f"{W}/DSC00222.JPG", "sample-rings", "craft", "Concentric hand-quilting on charcoal cotton"),
    (f"{W}/DSC00220.JPG", "sample-cross", "craft", "Quilted cross with wooden beads"),
    (f"{W}/DSC00221.JPG", "sample-knots", "craft", "French-knot texture sample"),
    # ---------- Kantha frame / embroidery ----------
    (f"{W}/DSC00192.JPG", "frame-stitch-01", "process", "Running stitch on a stretched frame"),
    (f"{W}/DSC00196.JPG", "frame-stitch-02", "process", "Kantha-style stitching on the frame"),
    (f"{W}/DSC00197.JPG", "frame-stitch-03", "process", "Rows of hand stitching"),
    (f"{W}/DSC00199.JPG", "frame-stitch-04", "process", "Hand embroidery on the frame"),
    (f"{W}/DSC00205.JPG", "zardozi-flower", "craft", "Velvet and metallic-thread zardozi motif"),
    (f"{W}/DSC00207.JPG", "beadwork-01", "process", "Bead and sequin embroidery by hand"),
    (f"{W}/DSC00209.JPG", "beadwork-02", "process", "Sequins, beads and bullion on red cotton"),
    (f"{W}/DSC00210.JPG", "beadwork-03", "process", "Hand-beading a motif"),
    (f"{W}/DSC00214.JPG", "zardozi-red", "process", "Zardozi embroidery on red silk"),
    # ---------- Block printing ----------
    (f"{W}/DSC00227.JPG", "blockprint-01", "process", "Hand block printing, one impression at a time"),
    (f"{W}/DSC00229.JPG", "blockprint-02", "process", "Registering the wooden block"),
    (f"{W}/DSC00232.JPG", "blockprint-03", "process", "A printer at the long table"),
    (f"{W}/DSC00236.JPG", "blockprint-04", "process", "Striking the block"),
    (f"{W}/DSC00231.JPG", "blockprint-sample", "craft", "A freshly printed geometric repeat"),
    (f"{W}/DSC00248.JPG", "blockprint-05", "process", "Printing a fine all-over pattern"),
    (f"{W}/DSC00250.JPG", "blockprint-06", "process", "Decades of practice in every strike"),
    (f"{W}/DSC00252.JPG", "blockprint-07", "process", "The master printer"),
    (f"{W}/DSC00254.JPG", "blockprint-08", "process", "Printing a mustard lattice"),
    (f"{W}/DSC00256.JPG", "blockprint-09", "process", "Block, dye tray, cloth"),
    (f"{W}/DSC00258.JPG", "blockprint-10", "process", "Two printers working a length"),
    (f"{W}/DSC00259.JPG", "blockprint-11", "process", "Charging the block with colour"),
    (f"{W}/DSC00261.JPG", "blockprint-cloth-01", "craft", "A mustard-and-madder block print, drying"),
    (f"{W}/DSC00263.JPG", "blockprint-12", "process", "Printing a border"),
    (f"{W}/DSC00266.JPG", "blockprint-13", "process", "Lifting the block"),
    (f"{W}/DSC00269.JPG", "blockprint-14", "process", "Printing side by side"),
    (f"{W}/DSC00271.JPG", "blockprint-15", "process", "Printing the second colour"),
    (f"{W}/DSC00274.JPG", "blockprint-16", "process", "Precision by eye"),
    (f"{W}/DSC00276.JPG", "blockprint-cloth-02", "craft", "Freshly printed cloth on the table"),
    (f"{W}/DSC00277.JPG", "blockprint-17", "process", "Checking the repeat"),
    (f"{W}/DSC00298.JPG", "blockprint-18", "process", "Printing a running motif"),
    (f"{W}/DSC00304.JPG", "blockprint-19", "process", "Layering colour on colour"),
    (f"{W}/DSC00305.JPG", "blockprint-20", "process", "Printing a red ground"),
    (f"{W}/DSC00312.JPG", "blockprint-21", "process", "Printing a resist pattern on indigo"),
    (f"{W}/DSC00313.JPG", "blockprint-22", "process", "Steady hands at the table"),
    # ---------- Washing & dyeing ----------
    (f"{W}/DSC00278.JPG", "washing-01", "process", "Washing printed cloth in the tank"),
    (f"{W}/DSC00280.JPG", "washing-02", "process", "Rinsing after printing"),
    (f"{W}/DSC00283.JPG", "washing-03", "process", "Washing by hand, in open air"),
    (f"{W}/DSC00286.JPG", "washing-04", "process", "Water, cloth, and light"),
    (f"{W}/DSC00287.JPG", "washing-05", "process", "Wringing out the cloth"),
    (f"{W}/DSC00291.JPG", "washing-06", "process", "Rinsing lengths of cotton"),
    (f"{W}/DSC00294.JPG", "washing-07", "process", "The washing tank under the trees"),
    (f"{W}/DSC00295.JPG", "washing-08", "process", "Washing in running water"),
    (f"{W}/DSC00318.JPG", "dyeing-01", "process", "Lifting cloth from the dye vat"),
    (f"{W}/DSC00321.JPG", "dyeing-02", "process", "Working the dye into the cloth"),
    (f"{W}/DSC00322.JPG", "dyeing-03", "process", "Indigo-dyed cloth, just out of the vat"),
    (f"{W}/DSC00328.JPG", "dyeing-04", "process", "Preparing the dye bath"),
    (f"{W}/DSC00330.JPG", "dyeing-05", "process", "The dyer at the copper vat"),
    (f"{W}/DSC00333.JPG", "dyeing-06", "process", "Stirring the vat"),
    (f"{W}/DSC00334.JPG", "dyeing-07", "process", "Carrying dye to the vat"),
    (f"{W}/DSC00337.JPG", "dyeing-08", "process", "Dyeing in a copper cauldron"),
    (f"{W}/DSC00339.JPG", "dyeing-09", "process", "Madder red in the vat"),
    (f"{W}/DSC00344.JPG", "dyeing-10", "process", "Beside the indigo tank"),
    (f"{W}/DSC00354.JPG", "dyeing-11", "process", "Rinsing dyed cloth"),
    (f"{W}/DSC00357.JPG", "dyeing-12", "process", "Rinsing after the dye bath"),
    # ---------- Old catalogue (late 1990s) ----------
    (f"{H}/blockprint1 - bed.jpg", "cat-blockprint-bed", "catalogue", "Indigo block-printed bed linen and cushions, from our first catalogue"),
    (f"{H}/emb1 - cushion cover.jpg", "cat-embroidered-cushions", "catalogue", "Hand-embroidered cushion covers"),
    ("Workshop_Sample Development/Artisan working/Copy of mfgprocess-of-blockprint.jpg", "cat-process-blockprint", "catalogue", "Block printing, as photographed for our first catalogue"),
    (f"{H}/mfgprocess-of-blockprint2.jpg", "cat-process-drying", "catalogue", "Lengths of red cloth drying in the sun"),
    ("Workshop_Sample Development/Artisan working/Copy of mfgprocess-of-emb(1st&secondleftonly).jpg", "cat-process-embroidery-2", "catalogue", "Embroidery and tie-dye in progress"),
    ("Workshop_Sample Development/Artisan working/Copy of mfgprocess-of-embrodary.jpg", "cat-process-embroidery", "catalogue", "Two embroiderers at work"),
    ("Workshop_Sample Development/Artisan working/Copy of mfgprocess-of-weaving(kharal).jpg", "cat-process-weaving", "catalogue", "Weaving a dhurrie on the ground loom"),
    (f"{H}/patchwork2 - catelogue.jpg", "cat-patchwork-cushions", "catalogue", "Patchwork cushions in blue and green"),
    (f"{H}/patchwork3 - bedcover,cushioncover,curtain.jpg", "cat-patchwork-bed", "catalogue", "Patchwork bedcover, cushions and curtain"),
    (f"{H}/patchwork4 - wall hanging (figure).jpg", "cat-wallhanging", "catalogue", "Appliqué wall hanging with figures and animals"),
    (f"{H}/quilts1 - gujarat.jpg", "cat-quilts", "catalogue", "Rolled hand-quilted throws from Gujarat"),
    (f"{H}/tie&dye2 - wine.jpg", "cat-tiedye-wine", "catalogue", "Bandhani tie-dye in wine"),
    (f"{H}/tie&dye3 - scarves.jpg", "cat-tiedye-scarves", "catalogue", "A pile of tie-dyed scarves"),
    (f"{H}/weaving1 - cottondari.jpg", "cat-dhurrie", "catalogue", "Hand-woven cotton dhurrie"),
    # ---------- Archive: Kantha (Bengal) ----------
    (f"{C}/KANTHA/107_3038.JPG", "arch-kantha-01", "archive", "Kantha with lattice ground and central lotus, Bengal"),
    (f"{C}/KANTHA/107_3039.JPG", "arch-kantha-02", "archive", "Kantha lotus medallion, detail"),
    (f"{C}/KANTHA/107_3040.JPG", "arch-kantha-03", "archive", "Red-on-white floral kantha"),
    (f"{C}/KANTHA/107_3042.JPG", "arch-kantha-04", "archive", "Scattered-flower kantha"),
    (f"{C}/KANTHA/107_3043.JPG", "arch-kantha-05", "archive", "Lotus-and-vine kantha, detail"),
    (f"{C}/KANTHA/IMG_4718.JPG", "arch-kantha-06", "archive", "Fine running-stitch kantha with paisleys"),
    (f"{C}/KANTHA/IMG_4719.JPG", "arch-kantha-07", "archive", "Kantha paisley, detail"),
    (f"{C}/KANTHA/IMG_4724.JPG", "arch-kantha-08", "archive", "Kantha with radiating petals"),
    (f"{C}/KANTHA 1/107_3300.JPG", "arch-kantha-09", "archive", "Figurative nakshi kantha"),
    (f"{C}/KANTHA 1/107_3310.JPG", "arch-kantha-10", "archive", "Kantha with sun-wheel medallion and borders"),
    (f"{C}/KANTHA 1/107_3311.JPG", "arch-kantha-11", "archive", "Sun-wheel kantha, detail"),
    (f"{C}/KANTHA 1/107_3313.JPG", "arch-kantha-12", "archive", "Densely stitched kantha medallion"),
    (f"{C}/KANTHA 1/107_3316.JPG", "arch-kantha-13", "archive", "Kantha with paisleys and quatrefoils"),
    (f"{C}/KANTHA 1/107_3317.JPG", "arch-kantha-14", "archive", "Kantha quatrefoils, detail"),
    # ---------- Archive: Patchwork & applique (Gujarat / Rajasthan) ----------
    (f"{C}/PATCH WORK/107_1292.JPG", "arch-applique-01", "archive", "Appliqué canopy with sun-wheel, Saurashtra"),
    (f"{C}/PATCH WORK/107_1295.JPG", "arch-applique-02", "archive", "Appliqué canopy, detail"),
    (f"{C}/PATCH WORK/107_1296.JPG", "arch-applique-03", "archive", "Appliqué sun-wheel"),
    (f"{C}/PATCH WORK/107_1298.JPG", "arch-applique-04", "archive", "Appliqué toran with hanging flaps"),
    (f"{C}/PATCH WORK/107_1300.JPG", "arch-applique-05", "archive", "Appliqué medallion, detail"),
    (f"{C}/PATCH WORK/107_2689.JPG", "arch-applique-06", "archive", "Pieced quilt with chevron border"),
    (f"{C}/PATCH WORK/107_2690.JPG", "arch-applique-07", "archive", "Pieced quilt of triangles and squares"),
    (f"{C}/PATCH WORK/107_2873.JPG", "arch-applique-08", "archive", "Embroidered and pieced chakla"),
    (f"{C}/PATCH WORK/107_3143.JPG", "arch-applique-09", "archive", "Appliqué hanging with tree of life"),
    (f"{C}/PATCH WORK/107_3144.JPG", "arch-applique-10", "archive", "Appliqué flowers, detail"),
    (f"{C}/PATCH WORK/107_3145.JPG", "arch-applique-11", "archive", "Appliqué tree of life"),
    (f"{C}/PATCH WORK/107_3146.JPG", "arch-applique-12", "archive", "Appliqué elephants, detail"),
    (f"{C}/PATCH WORK/107_3149.JPG", "arch-applique-13", "archive", "Appliqué sun-wheel on red"),
    (f"{C}/PATCH WORK/107_3151.JPG", "arch-applique-14", "archive", "Appliqué door hanging with elephants"),
    (f"{C}/PATCH WORK/107_3154.JPG", "arch-applique-15", "archive", "Appliqué garment"),
    (f"{C}/PATCH WORK/107_3208.JPG", "arch-applique-16", "archive", "Embroidered hanging with elephants and riders"),
    (f"{C}/PATCH WORK/107_3223.JPG", "arch-applique-17", "archive", "Embroidered runner with animals"),
    (f"{C}/PATCH WORK/107_3225.JPG", "arch-applique-18", "archive", "Embroidered medallions and horses, detail"),
    # ---------- Archive: Tie-dye / bandhani ----------
    (f"{C}/TIE DYE/107_3079.JPG", "arch-bandhani-01", "archive", "Embroidered garment on red"),
    (f"{C}/TIE DYE/107_3085.JPG", "arch-bandhani-02", "archive", "Fine bandhani in madder and black"),
    (f"{C}/TIE DYE/107_3086.JPG", "arch-bandhani-03", "archive", "Bandhani odhani"),
    (f"{C}/ekat & KE shawl/DSC04086.JPG", "arch-bandhani-04", "archive", "Bandhani with yellow and green dots"),
    (f"{C}/ekat & KE shawl/DSC04087.JPG", "arch-bandhani-05", "archive", "Bandhani, detail"),
    (f"{C}/ekat & KE shawl/DSC04089.JPG", "arch-bandhani-06", "archive", "Large-motif bandhani"),
    # ---------- Archive: Kashmir shawls ----------
    (f"{C}/kashmir shawl/100_0042.JPG", "arch-kashmir-01", "archive", "Kashmir moon shawl"),
    (f"{C}/kashmir shawl/100_0045.JPG", "arch-kashmir-02", "archive", "Kashmir long shawl with paisleys"),
    (f"{C}/kashmir shawl/100_0048.JPG", "arch-kashmir-03", "archive", "Kashmir shawl, centre detail"),
    (f"{C}/kashmir shawl/107_2099.JPG", "arch-kashmir-04", "archive", "Embroidered Kashmir shawl"),
    (f"{C}/kashmir shawl/107_2100.JPG", "arch-kashmir-05", "archive", "Kashmir shawl, corner"),
    (f"{C}/kashmir shawl/107_2815.JPG", "arch-kashmir-06", "archive", "Paisley shawl in blue and cream"),
    (f"{C}/kashmir shawl/107_2817.JPG", "arch-kashmir-07", "archive", "Paisley shawl, detail"),
    (f"{C}/kashmir shawl/107_2818.JPG", "arch-kashmir-08", "archive", "Paisley shawl border"),
    (f"{C}/kashmir shawl/107_2820.JPG", "arch-kashmir-09", "archive", "Woven paisley shawl"),
    (f"{C}/kashmir shawl/IMG_4247.JPG", "arch-kashmir-10", "archive", "Shawl border with floral vine"),
    # ---------- Archive: Mochi / Kalamkari / Brocade / Zari ----------
    (f"{C}/mochi embroidery/107_2674.JPG", "arch-mochi-01", "archive", "Mochi embroidered hanging, Kutch"),
    (f"{C}/mochi embroidery/107_2675.JPG", "arch-mochi-02", "archive", "Mochi embroidery, figures in medallion"),
    (f"{C}/mochi embroidery/107_2676.JPG", "arch-mochi-03", "archive", "Mochi embroidery with animals"),
    (f"{C}/mochi embroidery/107_2680.JPG", "arch-mochi-04", "archive", "Mochi embroidery, detail"),
    (f"{C}/mochiskirt/MOCHI_SKIRT1.jpg", "arch-mochi-skirt", "archive", "Red silk skirt with mochi embroidery"),
    (f"{C}/mochiskirt/MOCHI_SKIRT2.jpg", "arch-mochi-skirt-2", "archive", "Mochi embroidered skirt, detail"),
    (f"{C}/kamalkari south/107_2065.JPG", "arch-kalamkari-01", "archive", "Embroidered floral square"),
    (f"{C}/kamalkari south/107_2066.JPG", "arch-kalamkari-02", "archive", "Embroidered shawl with fringe"),
    (f"{C}/kamalkari south/107_2068.JPG", "arch-kalamkari-03", "archive", "Kalamkari hanging, South India"),
    (f"{C}/kamalkari south/107_2069.JPG", "arch-kalamkari-04", "archive", "Kalamkari hanging with figures"),
    (f"{C}/kamalkari south/107_2071.JPG", "arch-kalamkari-05", "archive", "Kalamkari panel"),
    (f"{C}/kamalkari south/107_2073.JPG", "arch-kalamkari-06", "archive", "Kalamkari, painted figures"),
    (f"{C}/kamalkari south/107_2076.JPG", "arch-kalamkari-07", "archive", "Kalamkari narrative panel"),
    (f"{C}/New Folder (2)/IMG_0014.jpg", "arch-brocade-01", "archive", "Purple and silver brocade"),
    (f"{C}/New Folder (2)/IMG_0017.jpg", "arch-brocade-02", "archive", "Red and gold brocade"),
    (f"{C}/New Folder (2)/IMG_0019.jpg", "arch-brocade-03", "archive", "Gold brocade with red border"),
    (f"{C}/New Folder (2)/IMG_0021.jpg", "arch-brocade-04", "archive", "Gold brocade"),
    (f"{C}/New Folder (2)/IMG_0022.jpg", "arch-brocade-05", "archive", "Red and gold brocade, detail"),
    (f"{C}/New Folder (2)/IMG_0025.jpg", "arch-brocade-06", "archive", "Purple brocade with animals"),
    (f"{C}/zari/107_2846.JPG", "arch-zari-01", "archive", "Zari embroidered panel"),
    # ---------- Archive: Patola & ikat ----------
    (f"{C}/ekat & KE shawl/DSC03810.JPG", "arch-patola-01", "archive", "Patola double-ikat, Patan"),
    (f"{C}/ekat & KE shawl/DSC03813.JPG", "arch-patola-02", "archive", "Framed patola in the weaver's home"),
    (f"{C}/ekat & KE shawl/DSC03816.JPG", "arch-patola-03", "archive", "Patola, detail"),
    (f"{C}/ekat & KE shawl/DSC03818.JPG", "arch-patola-04", "archive", "A patola weaver presents a sari"),
    (f"{C}/ekat & KE shawl/DSC03819.JPG", "arch-patola-05", "archive", "Patola star-lattice, detail"),
    (f"{C}/ekat & KE shawl/DSC03825.JPG", "arch-patola-06", "archive", "Elephant patola"),
    (f"{C}/ekat & KE shawl/DSC03827.JPG", "arch-patola-07", "archive", "Elephant patola, full length"),
    (f"{C}/ekat & KE shawl/DSC03829.JPG", "arch-patola-08", "archive", "Elephant patola, detail"),
    (f"{C}/ekat & KE shawl/DSC03830.JPG", "arch-patola-09", "archive", "Patola with tigers and elephants"),
    (f"{C}/ekat & KE shawl/DSC03836.JPG", "arch-patola-10", "archive", "The weaver and his patola"),
    (f"{C}/ekat & KE shawl/DSC03838.JPG", "arch-patola-11", "archive", "Patola, detail"),
    (f"{C}/ekat & KE shawl/DSC03843.JPG", "arch-patola-12", "archive", "Patola with dancing figures"),
    (f"{C}/ekat & KE shawl/DSC03845.JPG", "arch-patola-13", "archive", "Patola parrot motif"),
    (f"{C}/ekat & KE shawl/DSC03811.JPG", "arch-patola-loom", "archive", "The patola loom"),
    (f"{C}/ekat & KE shawl/DSC03873.JPG", "arch-patola-14", "archive", "Patola flower lattice"),
    (f"{C}/ekat & KE shawl/DSC03874.JPG", "arch-patola-15", "archive", "Patola with elaborate borders"),
    (f"{C}/ekat & KE shawl/DSC03879.JPG", "arch-patola-16", "archive", "Patola with cream field"),
    (f"{C}/ekat & KE shawl/DSC04065.JPG", "arch-shawl-01", "archive", "Embroidered shawl with medallion"),
    (f"{C}/ekat & KE shawl/DSC04067.JPG", "arch-shawl-02", "archive", "Kashmir shawl, paisley detail"),
    (f"{C}/ekat & KE shawl/DSC04071.JPG", "arch-painted-01", "archive", "Painted narrative cloth"),
    (f"{C}/ekat & KE shawl/DSC04077.JPG", "arch-ikat-01", "archive", "Ikat with painted border"),
    (f"{C}/ekat & KE shawl/DSC04083.JPG", "arch-embroidered-border", "archive", "Embroidered border with metallic thread"),
    (f"{C}/ekat & KE shawl/DSC04095.JPG", "arch-patola-17", "archive", "Patola star motif"),
    (f"{C}/ekat & KE shawl/DSC04097.JPG", "arch-patola-18", "archive", "Patola with lattice and flowers"),
    (f"{C}/ekat & KE shawl/DSC04102.JPG", "arch-mirror-01", "archive", "Mirror-work embroidery, Kutch"),
    (f"{C}/ekat & KE shawl/DSC04104.JPG", "arch-mirror-02", "archive", "Mirror-work embroidery, detail"),
]

# ---------------------------------------------------------------------------
# Second wave: the full archive (showroom, brochure, products, people, more
# of the antique collection). Optional 5th element: options dict
#   {"crop": (l, t, r, b) fractions kept, "ai": False, "rotate": deg, "wb": 0.3}
# ---------------------------------------------------------------------------
NP = "New Products"
L = "HCI/LINTAS"
CR = "Collection Old Textiles_Jewellery"
T = "Traditional Items"
WS = "Workshop_Sample Development"

PHOTOS += [
    # ---------- Brand, showroom, brochure ----------
    ("HCI/honeycomb-1.jpg", "showroom-hero", "place", "The Honeycomb showroom at Cama Hotel, Khanpur, Ahmedabad", {"ai": False}),
    ("HCI/IMG_0190.JPG", "showroom-01", "place", "Quilts and cushions on the showroom shelves"),
    ("HCI/IMG_0192.JPG", "showroom-02", "place", "The showroom"),
    ("HCI/IMG_0195.JPG", "showroom-03", "place", "Folded quilts, stacked by colour"),
    ("HCI/IMG_0198.JPG", "showroom-04", "place", "The showroom at Khanpur"),
    ("HCI/IMG_0201.JPG", "showroom-05", "place", "Bedcovers and throws on display"),
    ("HCI/IMG_0204.JPG", "showroom-06", "place", "Inside the showroom"),
    ("HCI/IMG_0206.JPG", "showroom-07", "place", "Cushions in the showroom"),
    ("HCI/DSC00712.jpg", "logo-on-cloth", "place", "The Honeycomb rider, embroidered on green cloth"),
    ("HCI/brochure-2012/WhatsApp Image 2026-08-27 at 9.01.42 PM.jpeg", "brochure-cover", "place", "Our 2012 brochure, Inspirations from Nature", {"crop": (0.0, 0.08, 1.0, 0.92)}),
    ("HCI/brochure-2012/WhatsApp Image 2026-08-27 at 9.01.55 PM.jpeg", "brochure-inside", "place", "Inside the brochure: Showcasing Craftsmanship since 1969"),
    ("HCI/WhatsApp Image 2026-08-27 at 9.02.54 PM.jpeg", "brochure-closed", "place", "The brochure, closed"),
    ("HCI/present-media/image1.jpeg", "prod-crinkle-blue", "product", "Crinkled tie-dye silk in peacock blue and green"),
    ("HCI/present-media/image2.jpeg", "prod-bandhani-black", "product", "Black-and-white bandhani silk, hand-knotted"),
    ("HCI/present-media/image3.jpeg", "prod-papier-mache", "product", "Hand-painted papier-mâché boxes, Kashmir"),
    ("HCI/present-media/image4.jpeg", "prod-cutwork-polaroids", "product", "White-on-white appliqué cutwork samples"),
    ("HCI/present-media/image5.jpeg", "prod-kantha-animal-cushions", "product", "Kantha-embroidered animal cushions"),
    # ---------- Sohel & family ----------
    ("Sohel/20140302_115006.jpg", "sohel-dye-pots", "people", "Sohel Weldingwala among the dye pots at a printing workshop, 2014"),
    ("Sohel/107_1237a.JPG", "sohel-portrait", "people", "Sohel Weldingwala at the showroom desk"),
    ("Sohel/20140302_115006 - Copya.jpg", "sohel-portrait-wall", "people", "Sohel Weldingwala"),
    ("Sohel/20140302_153514.jpg", "sohel-block", "people", "A hand-carved teak printing block"),
    ("Sohel/107_1237.JPG", "sohel-showroom-2007", "people", "At the showroom desk, 2007"),
    ("Sohel/20140302_114947.jpg", "dye-wall", "process", "The dyer's wall"),
    # ---------- Customers & visitors ----------
    ("Customers_Visitors/107_1304.JPG", "visitors-01", "people", "Buyers at the showroom table"),
    ("Customers_Visitors/107_1305.JPG", "visitors-02", "people", "Visitors in the showroom"),
    ("Customers_Visitors/107_2779.JPG", "visitors-03", "people", "A client visit"),
    ("Customers_Visitors/IMG_4673.JPG", "visitors-04", "people", "Clients in the showroom"),
    ("Customers_Visitors/107_1500.JPG", "visitors-05", "people", "Visitors at Honeycomb"),
    # ---------- Products: quilts ----------
    (f"{NP}/Quilts/Caravane Red Quilt.jpg", "prod-quilt-caravane", "product", "Red block-print quilt developed for Caravane, Paris"),
    (f"{NP}/Quilts/zara 2005 001.jpg", "prod-quilt-zara-1", "product", "Tie-dye striped quilts for Zara Home, 2005"),
    (f"{NP}/Quilts/zara 2005 004.jpg", "prod-quilt-zara-2", "product", "Tie-dye quilts, Zara Home 2005"),
    (f"{NP}/Quilts/Jharokha.jpg", "prod-quilt-jharokha", "product", "Jharokha quilt"),
    (f"{NP}/Quilts/Color Magic.JPG", "prod-quilt-colormagic", "product", "Colour Magic patchwork quilt"),
    (f"{NP}/Quilts/Milan Applique-1.jpg", "prod-quilt-milan", "product", "Milan appliqué quilt"),
    (f"{NP}/Quilts/P0000541.jpg", "prod-quilt-pieced-1", "product", "Hand-pieced triangle quilt"),
    (f"{NP}/Quilts/P0000543.jpg", "prod-quilt-pieced-2", "product", "Hand-pieced quilt, detail"),
    (f"{NP}/Quilts/Picture 003.jpg", "prod-quilt-green-1", "product", "Patchwork quilts"),
    (f"{NP}/Quilts/Picture 007.jpg", "prod-quilt-green-2", "product", "Patchwork quilt"),
    (f"{NP}/Quilts/IMG_3803.JPG", "prod-quilt-print-1", "product", "Block-printed patchwork quilt"),
    (f"{NP}/Quilts/IMG_3807.JPG", "prod-quilt-print-2", "product", "Block-printed patchwork quilt"),
    (f"{NP}/Quilts/IMG_3810.JPG", "prod-quilt-print-3", "product", "Block-printed quilt, detail"),
    (f"{NP}/Quilts/Bubble Quilt Indigo.jpg", "prod-quilt-indigo-1", "product", "Indigo bubble quilt"),
    (f"{NP}/Quilts/Indigo Quilts.jpg", "prod-quilt-indigo-2", "product", "Indigo quilts"),
    (f"{NP}/Quilts/Quilt Reve Print Indigo.jpg", "prod-quilt-indigo-3", "product", "Reverse-print indigo quilt"),
    (f"{NP}/Quilts/Quilt Star.jpg", "prod-quilt-star", "product", "Star quilt"),
    (f"{NP}/Quilts/WHT STAR QUILT.jpg", "prod-quilt-whitestar", "product", "White star quilt"),
    (f"{NP}/Quilts/Quilt Silk TD1.jpg", "prod-quilt-silk-td", "product", "Tie-dyed silk quilt"),
    (f"{NP}/Quilts/Quilt Leharia.jpg", "prod-quilt-leheria", "product", "Leheria silk quilt"),
    (f"{NP}/Quilts/Silk Shaded.jpg", "prod-quilt-silk-shaded", "product", "Shaded silk quilt"),
    (f"{NP}/Quilts/Quilt Kodi Chint.jpg", "prod-quilt-kodi", "product", "Kodi chintz quilt"),
    (f"{NP}/Quilts/Feathure Quilt.jpg", "prod-quilt-feather", "product", "Feather quilt"),
    (f"{NP}/Quilts/Quilt Jardin.jpg", "prod-quilt-jardin", "product", "Jardin quilt"),
    (f"{NP}/Quilts/Quilt Nippon.jpg", "prod-quilt-nippon", "product", "Nippon quilt"),
    (f"{NP}/Quilts/Wonderful front.jpg", "prod-quilt-wonderful", "product", "Wonderful quilt"),
    (f"{NP}/Quilts/Quilt Red Center.jpg", "prod-quilt-redcenter", "product", "Red-centre quilt"),
    (f"{NP}/Quilts/block-print-ajrak.jpg", "prod-quilt-ajrakh", "product", "Ajrakh block-print quilt"),
    (f"{L}/DSC00474.JPG", "prod-kantha-quilt-1", "product", "Hand-quilted indigo kantha bedcover"),
    (f"{L}/DSC00476.JPG", "prod-kantha-quilt-2", "product", "Indigo kantha quilt, detail"),
    (f"{L}/DSC00480.JPG", "prod-kantha-quilt-3", "product", "Striped kantha throw"),
    (f"{L}/DSC00483.JPG", "prod-kantha-quilt-4", "product", "Kantha quilts"),
    (f"{L}/DSC00487.JPG", "prod-kantha-quilt-5", "product", "Hand-stitched kantha bedcover"),
    (f"{L}/DSC00494.JPG", "prod-kantha-quilt-6", "product", "Kantha quilt"),
    (f"{L}/DSC00495.JPG", "prod-kantha-quilt-7", "product", "Kantha quilt, detail"),
    (f"{L}/DSC00496.JPG", "prod-kantha-quilt-8", "product", "Bandhani silk quilt"),
    (f"{L}/DSC00502.JPG", "prod-kantha-quilt-9", "product", "Rolled quilts"),
    (f"{L}/DSC00504.JPG", "prod-kantha-quilt-10", "product", "Quilts, folded"),
    (f"{L}/DSC00537.JPG", "prod-bedcover-applique-1", "product", "Indigo and madder appliqué bedcover"),
    (f"{L}/DSC00538.JPG", "prod-bedcover-applique-2", "product", "Appliqué bedcover, detail"),
    (f"{L}/DSC00539.JPG", "prod-bedcover-applique-3", "product", "Appliqué squares"),
    (f"{L}/DSC00534.JPG", "prod-cutwork-bedcover", "product", "White-on-white cutwork bedcover, detail"),
    (f"{L}/DSC00535.JPG", "prod-cutwork-bed", "product", "Cutwork bedcover on the bed"),
    (f"{L}/Quilt-5.jpg", "prod-quilt-rolled", "product", "Rolled quilts"),
    (f"{L}/Silk Leheria stripe-2.jpg", "prod-quilt-leheria-2", "product", "Leheria stripe silk quilt"),
    (f"{L}/Quilt-9a.jpg", "prod-quilt-9a", "product", "Kantha quilts"),
    # ---------- Products: cushions ----------
    (f"{NP}/Cushion Cover/107_1280.JPG", "prod-cushion-zardozi-1", "product", "Zardozi silk cushion"),
    (f"{NP}/Cushion Cover/107_1283.JPG", "prod-cushion-zardozi-2", "product", "Embroidered silk cushion"),
    (f"{NP}/Cushion Cover/107_1286.JPG", "prod-cushion-zardozi-3", "product", "Silk cushion with metal-thread embroidery"),
    (f"{NP}/Cushion Cover/107_2136.JPG", "prod-cushion-print-1", "product", "Block-printed cushion"),
    (f"{NP}/Cushion Cover/107_2140.JPG", "prod-cushion-print-2", "product", "Block-printed cushions"),
    (f"{NP}/Cushion Cover/107_2145.JPG", "prod-cushion-print-3", "product", "Block-printed floral cushion"),
    (f"{NP}/Cushion Cover/107_2150.JPG", "prod-cushion-print-4", "product", "Block-printed cushions"),
    (f"{NP}/Cushion Cover/104_0464.JPG", "prod-cushion-applique-1", "product", "Appliqué cushion"),
    (f"{NP}/Cushion Cover/104_0467.JPG", "prod-cushion-applique-2", "product", "Appliqué cushions"),
    (f"{NP}/Cushion Cover/IMG_4706.JPG", "prod-cushion-kantha-1", "product", "Kantha animal cushion"),
    (f"{NP}/Cushion Cover/IMG_4708.JPG", "prod-cushion-kantha-2", "product", "Kantha-embroidered cushions"),
    (f"{NP}/Cushion Cover/cushion covers 002.jpg", "prod-cushion-set", "product", "Cushion covers"),
    (f"{L}/tribal cushions.jpg", "prod-cushion-tribal", "product", "Tribal embroidered cushions"),
    (f"{L}/honycombcushion2.jpg", "prod-cushion-honeycomb", "product", "Embroidered cushion"),
    (f"{L}/Patchwork CC Tradnl.jpg", "prod-cushion-patchwork", "product", "Traditional patchwork cushion cover"),
    # ---------- Products: appliqué, cutwork, curtains, table ----------
    (f"{NP}/Applique Work_Patchwork/28May04 028.jpg", "prod-cutwork-1", "product", "White appliqué cutwork bedcover"),
    (f"{NP}/Applique Work_Patchwork/28May04 030.jpg", "prod-cutwork-2", "product", "Appliqué cutwork, detail"),
    (f"{NP}/Applique Work_Patchwork/28May04 042.jpg", "prod-cutwork-3", "product", "Cutwork bedcover"),
    (f"{NP}/Applique Work_Patchwork/28May04 047.jpg", "prod-cutwork-4", "product", "Cutwork, detail"),
    (f"{NP}/Applique Work_Patchwork/21june04 083.jpg", "prod-treeoflife-1", "product", "Tree of life appliqué panel"),
    (f"{NP}/Applique Work_Patchwork/21june04 086.jpg", "prod-treeoflife-2", "product", "Tree of life appliqué"),
    (f"{NP}/Applique Work_Patchwork/21june04 001.jpg", "prod-pieced-quilt", "product", "Pieced quilt"),
    (f"{NP}/Applique Work_Patchwork/IMG_4636.JPG", "prod-curtain-cutwork-1", "product", "Appliqué cutwork curtain"),
    (f"{NP}/Applique Work_Patchwork/IMG_4643.JPG", "prod-curtain-cutwork-2", "product", "Cutwork curtain in the window"),
    (f"{NP}/Applique Work_Patchwork/IMG_4653.JPG", "prod-curtain-cutwork-3", "product", "Cutwork curtains"),
    (f"{L}/Table Cloth-1.jpg", "prod-tablecloth-1", "product", "Cutwork tablecloth"),
    (f"{L}/Table cloth-3.jpg", "prod-tablecloth-3", "product", "White cutwork tablecloth"),
    (f"{L}/Tree.jpg", "prod-tree-cutwork", "product", "Tree of life cutwork panel"),
    (f"{L}/Milan Applique-2.jpg", "prod-milan-applique", "product", "Milan appliqué cushions"),
    (f"{L}/IMG_4637.JPG", "prod-cutwork-flowers", "product", "Appliqué flowers"),
    (f"{L}/IMG_4642.JPG", "prod-cutwork-lattice", "product", "Cutwork lattice"),
    (f"{NP}/Table Linen/107_2836.JPG", "prod-tablelinen-1", "product", "Block-printed table linen"),
    (f"{NP}/Table Linen/107_2838.JPG", "prod-tablelinen-2", "product", "Table linen"),
    (f"{NP}/Bed Covers/INDIGO (NATRUAL DYE) HAND BLOCK PRINTED.jpg", "prod-bedcover-indigo", "product", "Natural indigo hand block-printed bedcover"),
    (f"{NP}/Bed Covers/107_2839.JPG", "prod-bedcover-print", "product", "Block-printed bedcover"),
    # ---------- Products: block print & table covers ----------
    (f"{NP}/Print/20090408_002_TMDP.JPG", "prod-ajrakh-table-1", "product", "Ajrakh block-print table cover"),
    (f"{NP}/Print/20090408_006_TMDP.JPG", "prod-ajrakh-table-2", "product", "Block-printed table cover"),
    (f"{NP}/Print/20090408_009_TMDP.JPG", "prod-ajrakh-table-3", "product", "Ajrakh table cover, detail"),
    (f"{NP}/Print/20090408_013_TMDP.JPG", "prod-ajrakh-table-4", "product", "Block-printed table cover"),
    (f"{NP}/Print/20090408_020_TMDP.JPG", "prod-ajrakh-table-5", "product", "Block-printed cloth"),
    (f"{NP}/Print/20090408_033_TMDP.JPG", "prod-ajrakh-table-6", "product", "Block-printed table cover"),
    (f"{NP}/Print/20090408_072_TMDP.JPG", "prod-ajrakh-table-7", "product", "Block print on the table"),
    (f"{NP}/Print/20090408_086_TMDP.JPG", "prod-ajrakh-table-8", "product", "Block-printed table cover"),
    (f"{WS}/DSC00359.JPG", "prod-print-swatch-1", "product", "Indigo block-print swatches"),
    (f"{WS}/DSC00361.JPG", "prod-print-swatch-2", "product", "Indigo prints"),
    (f"{WS}/DSC00363.JPG", "prod-print-swatch-3", "product", "Mustard and indigo geometric prints"),
    (f"{WS}/DSC00365.JPG", "prod-print-swatch-4", "product", "Geometric block prints"),
    (f"{L}/Print-1.jpg", "prod-print-cushions", "product", "Block-printed cushions"),
    (f"{L}/Printed Quilts.jpg", "prod-printed-quilts", "product", "Printed quilts"),
    (f"{L}/P0001123.jpg", "prod-print-patch-1", "product", "Block-print patchwork"),
    (f"{L}/P0001130.jpg", "prod-print-patch-2", "product", "Indigo patchwork"),
    # ---------- Products: tie-dye, scarves, bags ----------
    (f"{L}/DSC00547.JPG", "prod-scarf-crinkle-1", "product", "Crinkled silk scarves"),
    (f"{L}/DSC00549.JPG", "prod-scarf-crinkle-2", "product", "Crinkle silk in saffron and pink"),
    (f"{L}/DSC00551.JPG", "prod-scarf-crinkle-3", "product", "Crinkle silk in olive"),
    (f"{L}/DSC00553.JPG", "prod-scarf-rolls-1", "product", "Silk scarves, rolled"),
    (f"{L}/DSC00556.JPG", "prod-shibori-1", "product", "Shibori silk"),
    (f"{L}/DSC00565.JPG", "prod-bandhani-pink", "product", "Pink bandhani silk"),
    (f"{L}/DSC00569.JPG", "prod-bandhani-teal", "product", "Bandhani in teal"),
    (f"{L}/DSC00571.JPG", "prod-scarf-stack", "product", "Bandhani silk stoles"),
    (f"{L}/DSC00580.JPG", "prod-scarf-rolls-2", "product", "Tie-dye scarves, rolled"),
    (f"{L}/DSC00586.JPG", "prod-bandhani-rose", "product", "Rose bandhani"),
    (f"{L}/DSC00589.JPG", "prod-bandhani-paisley", "product", "Bandhani paisley on silk"),
    (f"{L}/DSC00592.JPG", "prod-bandhani-paisley-2", "product", "Bandhani paisley, detail"),
    (f"{L}/DSC00594.JPG", "prod-shibori-olive", "product", "Olive shibori silk"),
    (f"{L}/DSC00596.JPG", "prod-shibori-gold", "product", "Gold shibori silk"),
    (f"{NP}/Tie Dye/IMG_0724.JPG", "prod-shibori-black", "product", "Black shibori silk"),
    (f"{NP}/Tie Dye/IMG_0790.JPG", "prod-tiedye-1", "product", "Tie-dyed silk"),
    (f"{NP}/Tie Dye/IMG_0806.JPG", "prod-tiedye-2", "product", "Tie-dyed silk"),
    (f"{NP}/Tie Dye/IMG_0816.JPG", "prod-tiedye-3", "product", "Tie-dye"),
    (f"{NP}/Tie Dye/20140302_224414.jpg", "prod-tiedye-4", "product", "Tie-dyed silk"),
    (f"{NP}/Fashion Accessories (Scarves_Bags)/20140128_142934.jpg", "prod-bag-1", "product", "Embroidered bag, Kutch"),
    (f"{NP}/Fashion Accessories (Scarves_Bags)/20140128_143046.jpg", "prod-bag-2", "product", "Embroidered bag"),
    (f"{NP}/Fashion Accessories (Scarves_Bags)/20140128_143359.jpg", "prod-bag-3", "product", "Embroidered bag"),
    (f"{NP}/Fashion Accessories (Scarves_Bags)/20140128_143500.jpg", "prod-bag-4", "product", "Embroidered clutch"),
    (f"{NP}/Fashion Accessories (Scarves_Bags)/20140128_144008.jpg", "prod-bag-5", "product", "Mirror-work bag"),
    (f"{NP}/Fashion Accessories (Scarves_Bags)/20140128_144842.jpg", "prod-bag-6", "product", "Embroidered bag"),
    (f"{NP}/Fashion Accessories (Scarves_Bags)/20140128_145405.jpg", "prod-bag-7", "product", "Embroidered bag"),
    (f"{NP}/Fashion Accessories (Scarves_Bags)/20140227_114406.jpg", "prod-scarf-1", "product", "Scarves"),
    (f"{NP}/Fashion Accessories (Scarves_Bags)/20140227_120134.jpg", "prod-scarf-2", "product", "Scarves"),
    (f"{NP}/Fashion Accessories (Scarves_Bags)/20140227_151326.jpg", "prod-scarf-3", "product", "Scarves"),
    # ---------- Products: wall hangings & embroidery ----------
    (f"{NP}/Wall Hanging/107_2611.JPG", "prod-hanging-1", "product", "Embroidered wall hanging"),
    (f"{NP}/Wall Hanging/107_2617.JPG", "prod-hanging-2", "product", "Appliqué wall hanging"),
    (f"{NP}/Wall Hanging/107_2625.JPG", "prod-hanging-3", "product", "Wall hanging"),
    (f"{NP}/Wall Hanging/107_2640.JPG", "prod-hanging-4", "product", "Embroidered wall hanging"),
    (f"{NP}/Wall Hanging/107_2645.JPG", "prod-hanging-5", "product", "Wall hanging"),
    (f"{NP}/Wall Hanging/22[1].Sohel_s applique wall hanging.JPG", "prod-hanging-sohel", "product", "Appliqué wall hanging designed by Sohel"),
    (f"{NP}/Wall Hanging/wall-hanging.jpg", "prod-hanging-6", "product", "Appliqué wall hanging"),
    (f"{NP}/Wall Hanging/patchwork-fig.jpg", "prod-hanging-figures", "product", "Figurative appliqué hanging"),
    (f"{NP}/Wall Hanging/107_1495.JPG", "prod-hanging-7", "product", "Wall hanging"),
    (f"{NP}/Wall Hanging/107_2505.JPG", "prod-hanging-8", "product", "Wall hanging"),
    (f"{NP}/Wall Hanging/107_2528.JPG", "prod-hanging-9", "product", "Wall hanging"),
    (f"{NP}/Embroidery/107_1232a.jpg", "prod-embroidery-1", "product", "Hand embroidery"),
    (f"{NP}/Embroidery/IMG_4512.JPG", "prod-embroidery-2", "product", "Hand embroidery"),
    # ---------- Traditional items ----------
    (f"{T}/20140128_163409.jpg", "trad-01", "archive", "Antique embroidered chakla, Kutch"),
    (f"{T}/20140128_163647.jpg", "trad-02", "archive", "Embroidered square, Saurashtra"),
    (f"{T}/20140128_163716.jpg", "trad-03", "archive", "Mirror-work embroidery"),
    (f"{T}/20140128_163801.jpg", "trad-04", "archive", "Embroidered hanging"),
    (f"{T}/20140128_163848.jpg", "trad-05", "archive", "Embroidered textile"),
    (f"{T}/20140128_163939.jpg", "trad-06", "archive", "Embroidered textile"),
    (f"{T}/20131118_171921.jpg", "trad-07", "archive", "Traditional embroidery"),
    (f"{T}/IMG_3372.JPG", "trad-08", "archive", "Antique embroidered cushion cover"),
    (f"{T}/IMG_3375.JPG", "trad-09", "archive", "Antique embroidered textile"),
    (f"{T}/IMG_3378.JPG", "trad-10", "archive", "Embroidered chakla"),
    (f"{T}/IMG_3381.JPG", "trad-11", "archive", "Embroidered square"),
    (f"{T}/IMG_4189.JPG", "trad-12", "archive", "Antique textile"),
    (f"{T}/IMG_0894.jpg", "trad-13", "archive", "Traditional textile"),
    # ---------- Archive: more ----------
    (f"{CR}/100_0082.JPG", "arch-kashmir-11", "archive", "Kashmir moon shawl, centre medallion"),
    (f"{CR}/100_0085.JPG", "arch-kashmir-12", "archive", "Kashmir shawl, detail"),
    (f"{CR}/100_0077.JPG", "arch-kashmir-13", "archive", "Kashmir shawl with paisley corners"),
    (f"{CR}/100_0079.JPG", "arch-kashmir-14", "archive", "Kashmir shawl"),
    (f"{CR}/101_0162.JPG", "arch-phulkari-01", "archive", "Phulkari, Punjab"),
    (f"{CR}/20130917_124010.jpg", "arch-phulkari-02", "archive", "Phulkari border"),
    (f"{CR}/20130917_124242.jpg", "arch-phulkari-03", "archive", "Phulkari bagh"),
    (f"{CR}/20130917_124455.jpg", "arch-phulkari-04", "archive", "Phulkari, detail"),
    (f"{CR}/20130917_125006.jpg", "arch-phulkari-05", "archive", "Phulkari with diamond lattice"),
    (f"{CR}/20130917_125404.jpg", "arch-phulkari-06", "archive", "Phulkari bagh, detail"),
    (f"{CR}/IMG_3412.JPG", "arch-phulkari-07", "archive", "Phulkari bagh"),
    (f"{CR}/IMG_3414.JPG", "arch-phulkari-08", "archive", "Phulkari bagh, detail"),
    (f"{CR}/105_0536.JPG", "arch-canopy-01", "archive", "Embroidered canopy tent, Saurashtra"),
    (f"{CR}/105_0538.JPG", "arch-canopy-02", "archive", "Embroidered canopy"),
    (f"{CR}/107_2780.JPG", "arch-frieze-01", "archive", "Embroidered frieze with animals, Saurashtra"),
    (f"{CR}/107_2784.JPG", "arch-frieze-02", "archive", "Embroidered frieze with riders"),
    (f"{CR}/107_2786.JPG", "arch-frieze-03", "archive", "Embroidered frieze with animals"),
    (f"{CR}/107_2788.JPG", "arch-frieze-04", "archive", "Embroidered frieze with geometric bands"),
    (f"{CR}/IMG_0070.JPG", "arch-kalamkari-10", "archive", "Kalamkari prayer cloth"),
    (f"{CR}/IMG_0083.JPG", "arch-kalamkari-11", "archive", "Kalamkari with animals"),
    (f"{CR}/IMG_0096.JPG", "arch-kalamkari-12", "archive", "Kalamkari with calligraphy"),
    (f"{CR}/IMG_0099.JPG", "arch-kalamkari-13", "archive", "Kalamkari prayer cloth with cypress"),
    (f"{CR}/IMG_0113.JPG", "arch-kalamkari-14", "archive", "Kalamkari border"),
    (f"{CR}/IMG_0132.JPG", "arch-kalamkari-15", "archive", "Kalamkari with portrait medallions"),
    (f"{CR}/IMG_0146.JPG", "arch-kalamkari-16", "archive", "Kalamkari with lotus vine"),
    (f"{CR}/IMG_0149.JPG", "arch-kalamkari-17", "archive", "Kalamkari with animals"),
    (f"{CR}/IMG_0161.JPG", "arch-kalamkari-18", "archive", "Kalamkari with palms"),
    (f"{CR}/IMG_0165.JPG", "arch-kalamkari-19", "archive", "Kalamkari, detail"),
    (f"{CR}/TEXTILE/KALAMKARI MASULIPATTAM/107_3979.JPG", "arch-kalamkari-20", "archive", "Kalamkari, Masulipatnam"),
    (f"{CR}/TEXTILE/KALAMKARI MASULIPATTAM/107_3983.JPG", "arch-kalamkari-21", "archive", "Kalamkari, Masulipatnam"),
    (f"{CR}/TEXTILE/KALAMKARI MASULIPATTAM/107_3999.JPG", "arch-kalamkari-22", "archive", "Kalamkari, detail"),
    (f"{CR}/TEXTILE/KALAMKARI MASULIPATTAM/107_4002.JPG", "arch-kalamkari-23", "archive", "Kalamkari prayer cloth"),
    (f"{CR}/TEXTILE/BLOCK PRINT/107_2856.JPG", "arch-blockprint-01", "archive", "Antique block-printed cloth"),
    (f"{CR}/TEXTILE/BLOCK PRINT/107_2861.JPG", "arch-blockprint-02", "archive", "Block print, detail"),
    (f"{CR}/TEXTILE/BLOCK PRINT/107_2867.JPG", "arch-blockprint-03", "archive", "Block-printed floral"),
    (f"{CR}/TEXTILE/BLOCK PRINT/107_2870.JPG", "arch-blockprint-04", "archive", "Block-printed border"),
    (f"{CR}/TEXTILE/BLOCK PRINT/107_3324.JPG", "arch-blockprint-05", "archive", "Block-printed cloth"),
    (f"{CR}/TEXTILE/BLOCK PRINT/107_3328.JPG", "arch-blockprint-06", "archive", "Block print, detail"),
    (f"{CR}/TEXTILE/2008_02_14/107_2941.JPG", "arch-painted-02", "archive", "Painted narrative cloth"),
    (f"{CR}/TEXTILE/2008_02_14/107_2946.JPG", "arch-painted-03", "archive", "Painted narrative cloth, detail"),
    (f"{CR}/TEXTILE/2008_02_14/107_2948.JPG", "arch-painted-04", "archive", "Painted cloth with riders"),
    (f"{CR}/TEXTILE/2008_02_14/107_2950.JPG", "arch-painted-05", "archive", "Painted cloth, detail"),
    (f"{CR}/TEXTILE/2008_04_12/107_3044.JPG", "arch-painted-06", "archive", "Painted narrative panel"),
    (f"{CR}/TEXTILE/2008_04_12/107_3047.JPG", "arch-painted-07", "archive", "Painted panel, detail"),
    (f"{CR}/TEXTILE/2008_04_12/107_3050.JPG", "arch-painted-08", "archive", "Painted panel with figures"),
    (f"{CR}/TEXTILE/2008_04_14/107_3055.JPG", "arch-zardozi-01", "archive", "Zardozi skirt"),
    (f"{CR}/TEXTILE/2008_04_14/107_3061.JPG", "arch-chintz-01", "archive", "Printed chintz"),
    (f"{CR}/TEXTILE/2008_04_16/107_3068.JPG", "arch-zardozi-02", "archive", "Zardozi square"),
    (f"{CR}/TEXTILE/FILE0331.JPG", "arch-zardozi-03", "archive", "Zardozi on velvet"),
    (f"{CR}/TEXTILE/FILE0335.JPG", "arch-zardozi-04", "archive", "Zardozi on velvet, detail"),
    (f"{CR}/TEXTILE/FILE0338.JPG", "arch-zardozi-05", "archive", "Zardozi hunting scene on velvet"),
    (f"{CR}/TEXTILE/FILE0343.JPG", "arch-zardozi-06", "archive", "Zardozi coat"),
    (f"{CR}/20140116_143248.jpg", "arch-zardozi-07", "archive", "Gold zardozi on black"),
    (f"{CR}/20140116_143412.jpg", "arch-zardozi-08", "archive", "Zardozi bodice"),
    (f"{CR}/20140114_112427.jpg", "arch-zardozi-09", "archive", "Embroidered square with red border"),
    (f"{CR}/20140114_130136.jpg", "arch-jewel-01", "archive", "Silver necklace"),
    (f"{CR}/20140114_130335.jpg", "arch-jewel-02", "archive", "Silver necklace"),
    (f"{CR}/20140125_120432.jpg", "arch-toran-01", "archive", "Embroidered toran"),
    (f"{CR}/20140125_120525.jpg", "arch-toran-02", "archive", "Toran, detail"),
    (f"{CR}/IMG_4696.JPG", "arch-kantha-15", "archive", "Figurative kantha with horse and rider"),
    (f"{CR}/IMG_4698.JPG", "arch-kantha-16", "archive", "Kantha with figures"),
    (f"{CR}/IMG_4712.JPG", "arch-phulkari-09", "archive", "Phulkari bagh"),
    (f"{CR}/IMG_4734.JPG", "arch-frieze-05", "archive", "Embroidered hanging with animals"),
    (f"{CR}/IMG_4740.JPG", "arch-frieze-06", "archive", "Embroidered hanging"),
    (f"{CR}/IMG_4746.JPG", "arch-frieze-07", "archive", "Embroidered hanging with lattice"),
    (f"{CR}/TEXTILE/2009_03_02/107_3575.JPG", "arch-mirror-03", "archive", "Mirror-work embroidery"),
    (f"{CR}/TEXTILE/2009_03_02/107_3577.JPG", "arch-mirror-04", "archive", "Mirror-work with peacocks"),
    (f"{CR}/TEXTILE/2009_03_02/107_3579.JPG", "arch-mirror-05", "archive", "Mirror-work square"),
    (f"{CR}/TEXTILE/glass bead work/107_2917.JPG", "arch-beadwork-01", "archive", "Glass beadwork, Saurashtra"),
    (f"{CR}/TEXTILE/glass bead work/107_2919.JPG", "arch-beadwork-02", "archive", "Glass beadwork, detail"),
    (f"{CR}/TEXTILE/2008_05_16/107_3211.JPG", "arch-embroidered-square-01", "archive", "Embroidered square with gold border"),
    (f"{CR}/TEXTILE/2008_05_16/107_3212.JPG", "arch-embroidered-square-02", "archive", "Embroidered square"),
    (f"{CR}/TEXTILE/2008_05_16/107_3214.JPG", "arch-embroidered-square-03", "archive", "Embroidered square"),
    (f"{CR}/TEXTILE/Ikat 1.jpg", "arch-ikat-02", "archive", "Ikat"),
    (f"{CR}/TEXTILE/KANTHA 1.jpg", "arch-kantha-17", "archive", "Figurative kantha"),
    (f"{CR}/TEXTILE/Kantha.jpg", "arch-kantha-18", "archive", "Kantha elephant"),
    (f"{CR}/TEXTILE/palkhi0005.jpg", "arch-palkhi", "archive", "Embroidered palanquin"),
    # ---------- Workshop extras ----------
    (f"{WS}/DSC00453.JPG", "kutch-embroidery-01", "people", "Embroiderers in a Kutch village"),
    (f"{WS}/DSC00456.JPG", "kutch-embroidery-02", "people", "Embroidering by hand, Kutch"),
    (f"{WS}/DSC00459.JPG", "kutch-embroidery-03", "people", "Embroiderers at work"),
    (f"{WS}/DSC00460.JPG", "kutch-elder", "people", "A village elder, Kutch"),
    (f"{WS}/DSC00463.JPG", "kutch-women", "people", "Women of a Kutch village"),
    (f"{WS}/DSC00465.JPG", "kutch-quilt", "people", "A finished quilt outside a bhunga"),
    (f"{WS}/DSC00444.JPG", "kutch-bhunga-01", "people", "A bhunga home in Kutch"),
    (f"{WS}/DSC00449.JPG", "kutch-bhunga-02", "people", "Village home, Kutch"),
    (f"{WS}/DSC00300.JPG", "blockprint-23", "process", "Printing at the long table"),
    (f"{WS}/DSC00306.JPG", "blockprint-24", "process", "A young printer at work"),
    (f"{WS}/DSC00310.JPG", "blockprint-25", "process", "Printing ajrakh"),
    (f"{WS}/DSC00341.JPG", "dyeing-13", "process", "Lifting madder-dyed cloth from the vat"),
    (f"{WS}/DSC00348.JPG", "washing-09", "process", "Washing red cloth"),
    (f"{WS}/DSC00350.JPG", "washing-10", "process", "Rinsing in running water"),
    (f"{WS}/DSC00223.JPG", "pattern-drawing", "process", "Drawing a pattern with compass"),
    (f"{WS}/IMG_4831.JPG", "block-carving", "process", "Carving a printing block"),
    (f"{WS}/20140302_112320.jpg", "dye-pots-01", "process", "Pigment pots"),
    (f"{WS}/20140302_112331.jpg", "dye-pots-02", "process", "Dye pots in colour"),
    (f"{WS}/20140302_124702.jpg", "blockprint-26", "process", "A block on the printed cloth"),
    (f"{WS}/20140302_120415.jpg", "blockprint-27", "process", "Red floral block print"),
    (f"{WS}/20131001_190234.jpg", "cutwork-table", "process", "Checking a cutwork bedcover"),
    (f"{WS}/20140123_131259.jpg", "stitching-black", "process", "Hand-stitching"),
]

# ---------------------------------------------------------------------------
# New designs for 2026 (HCI/LINTAS/New Dsgn26) and the artisan folder
# ---------------------------------------------------------------------------
ND = "HCI/LINTAS/New Dsgn26"
AW = "Workshop_Sample Development/Artisan working"
PHOTOS += [
    (f"{ND}/Bale 2 Indigo Outlin.jpeg", "prod-quilt-2026-indigo", "product", "New for 2026: hand-quilted indigo paisley bedcover with striped reverse"),
    (f"{ND}/Bale 2 Orng.jpeg", "prod-quilt-2026-terracotta", "product", "New for 2026: terracotta block-print quilt, hand-stitched"),
    (f"{ND}/Bale1 3 colors.jpeg", "prod-quilt-2026-trio", "product", "New for 2026: mustard, stone and taupe block-print quilts"),
    (f"{ND}/Bale1 3colors.jpeg", "prod-quilt-2026-teal", "product", "New for 2026: teal, mustard and stone quilts, rolled"),
    (f"{ND}/Bale1 4 colors.jpeg", "prod-quilt-2026-four", "product", "New for 2026: four colourways of the floral quilt"),
    (f"{ND}/Bale2 Stone.jpeg", "prod-quilt-2026-stone", "product", "New for 2026: stone-on-white paisley quilt"),
    (f"{ND}/Block Print Line.jpeg", "blockprint-2026-line", "process", "Printing a fine stripe, 2026"),
    (f"{ND}/Block Printing Dia.jpeg", "blockprint-2026-dia", "process", "Registering a block on a striped ground"),
    (f"{AW}/Washing Fabric.jpeg", "washing-2026", "process", "Washing printed cloth in the tank"),
    (f"{AW}/20140123_131241.jpg", "artisan-stitching", "process", "Hand-stitching on a striped ground"),
    (f"{AW}/20140222_203827.jpg", "artisan-loom-01", "process", "At the loom"),
    (f"{AW}/20140222_203836.jpg", "artisan-loom-02", "process", "Weaving by hand"),
    (f"{AW}/20140302_111901.jpg", "artisan-dye-01", "process", "Mixing pigment by hand"),
    (f"{AW}/20140302_111911.jpg", "artisan-dye-02", "process", "Pigment pots on the dyer's bench"),
]
