"""
Curated photo manifest for honeycombint.com.

Each entry: (source path relative to the archive folder, output slug, group, caption)
Groups: process | craft | archive | people | catalogue
"""

W = "Workshop_Sample Development"
C = "Collection Old Textiles_Jewellery/TEXTILE"
H = "HCI/website"

PHOTOS = [
    # ---------- Hand quilting / kantha stitching ----------
    (f"{W}/DSC00162.JPG", "quilting-01", "process", "Hand-quilting a cotton bedcover, stitch by stitch"),
    (f"{W}/DSC00172.JPG", "quilting-02", "process", "Running stitch through layers of soft cotton"),
    (f"{W}/DSC00173.JPG", "quilting-03", "process", "An artisan hand-quilting in the workshop"),
    (f"{W}/DSC00170.JPG", "quilting-hands", "process", "The needle and the thread, close up"),
    (f"{W}/DSC00395.JPG", "village-quilting-01", "people", "Village women hand-quilting block-printed cloth"),
    (f"{W}/DSC00398.JPG", "village-quilting-02", "people", "A circle of quilters at work"),
    (f"{W}/DSC00401.JPG", "village-quilting-03", "people", "Quilting under the open sky"),
    (f"{W}/DSC00402.JPG", "village-quilting-04", "people", "Hand-quilting a block-printed quilt"),
    (f"{W}/DSC00409.JPG", "village-quilting-05", "people", "Quilting by hand"),
    (f"{W}/DSC00418.JPG", "village-quilting-06", "process", "Bangled hands over hand-stitched cloth"),
    (f"{W}/DSC00419.JPG", "village-quilting-07", "people", "Every quilt is finished by hand"),
    (f"{W}/DSC00447.JPG", "village-hut", "people", "A mud-and-thatch home where quilters work"),
    # ---------- Applique / patchwork ----------
    (f"{W}/DSC00181.JPG", "applique-cut-01", "process", "Cutting appliqué motifs with heavy iron shears"),
    (f"{W}/DSC00184.JPG", "applique-cut-02", "process", "Freehand cutting, no template"),
    (f"{W}/DSC00186.JPG", "applique-cut-03", "process", "Cutting the appliqué"),
    (f"{W}/DSC00188.JPG", "applique-lay-01", "process", "Laying out cut-work before stitching"),
    (f"{W}/DSC00190.JPG", "applique-lay-02", "process", "Placing appliqué pieces on the ground cloth"),
    (f"{W}/DSC00200.JPG", "spiral-01", "process", "Hand-stitching a spiral appliqué"),
    (f"{W}/DSC00202.JPG", "spiral-02", "process", "Spiral appliqué in progress"),
    (f"{W}/DSC00203.JPG", "spiral-03", "process", "The spiral takes shape"),
    (f"{W}/DSC00225.JPG", "sample-spiral", "craft", "Finished spiral appliqué cushion sample"),
    (f"{W}/DSC00218.JPG", "sample-circles", "craft", "Quilted circles, sample development"),
    (f"{W}/DSC00222.JPG", "sample-rings", "craft", "Concentric hand-quilting on charcoal cotton"),
    (f"{W}/DSC00220.JPG", "sample-cross", "craft", "Quilted cross with wooden beads"),
    (f"{W}/DSC00221.JPG", "sample-knots", "craft", "French-knot texture sample"),
    # ---------- Kantha frame / embroidery ----------
    (f"{W}/DSC00192.JPG", "frame-stitch-01", "process", "Running stitch on a stretched frame"),
    (f"{W}/DSC00196.JPG", "frame-stitch-02", "process", "Kantha-style stitching on the frame"),
    (f"{W}/DSC00197.JPG", "frame-stitch-03", "process", "Rows of hand stitching"),
    (f"{W}/DSC00199.JPG", "frame-stitch-04", "process", "Hand embroidery on the frame"),
    (f"{W}/DSC00205.JPG", "zardozi-flower", "craft", "Velvet and metallic-thread zardozi motif"),
    (f"{W}/DSC00207.JPG", "beadwork-01", "process", "Bead and sequin embroidery by hand"),
    (f"{W}/DSC00209.JPG", "beadwork-02", "process", "Sequins, beads and bullion on red cotton"),
    (f"{W}/DSC00210.JPG", "beadwork-03", "process", "Hand-beading a motif"),
    (f"{W}/DSC00214.JPG", "zardozi-red", "process", "Zardozi embroidery on red silk"),
    # ---------- Block printing ----------
    (f"{W}/DSC00227.JPG", "blockprint-01", "process", "Hand block printing, one impression at a time"),
    (f"{W}/DSC00229.JPG", "blockprint-02", "process", "Registering the wooden block"),
    (f"{W}/DSC00232.JPG", "blockprint-03", "process", "A printer at the long table"),
    (f"{W}/DSC00236.JPG", "blockprint-04", "process", "Striking the block"),
    (f"{W}/DSC00231.JPG", "blockprint-sample", "craft", "A freshly printed geometric repeat"),
    (f"{W}/DSC00248.JPG", "blockprint-05", "process", "Printing a fine all-over pattern"),
    (f"{W}/DSC00250.JPG", "blockprint-06", "process", "Decades of practice in every strike"),
    (f"{W}/DSC00252.JPG", "blockprint-07", "process", "The master printer"),
    (f"{W}/DSC00254.JPG", "blockprint-08", "process", "Printing a mustard lattice"),
    (f"{W}/DSC00256.JPG", "blockprint-09", "process", "Block, dye tray, cloth"),
    (f"{W}/DSC00258.JPG", "blockprint-10", "process", "Two printers working a length"),
    (f"{W}/DSC00259.JPG", "blockprint-11", "process", "Charging the block with colour"),
    (f"{W}/DSC00261.JPG", "blockprint-cloth-01", "craft", "A mustard-and-madder block print, drying"),
    (f"{W}/DSC00263.JPG", "blockprint-12", "process", "Printing a border"),
    (f"{W}/DSC00266.JPG", "blockprint-13", "process", "Lifting the block"),
    (f"{W}/DSC00269.JPG", "blockprint-14", "process", "Printing side by side"),
    (f"{W}/DSC00271.JPG", "blockprint-15", "process", "Printing the second colour"),
    (f"{W}/DSC00274.JPG", "blockprint-16", "process", "Precision by eye"),
    (f"{W}/DSC00276.JPG", "blockprint-cloth-02", "craft", "Freshly printed cloth on the table"),
    (f"{W}/DSC00277.JPG", "blockprint-17", "process", "Checking the repeat"),
    (f"{W}/DSC00298.JPG", "blockprint-18", "process", "Printing a running motif"),
    (f"{W}/DSC00304.JPG", "blockprint-19", "process", "Layering colour on colour"),
    (f"{W}/DSC00305.JPG", "blockprint-20", "process", "Printing a red ground"),
    (f"{W}/DSC00312.JPG", "blockprint-21", "process", "Printing a resist pattern on indigo"),
    (f"{W}/DSC00313.JPG", "blockprint-22", "process", "Steady hands at the table"),
    # ---------- Washing & dyeing ----------
    (f"{W}/DSC00278.JPG", "washing-01", "process", "Washing printed cloth in the tank"),
    (f"{W}/DSC00280.JPG", "washing-02", "process", "Rinsing after printing"),
    (f"{W}/DSC00283.JPG", "washing-03", "process", "Washing by hand, in open air"),
    (f"{W}/DSC00286.JPG", "washing-04", "process", "Water, cloth, and light"),
    (f"{W}/DSC00287.JPG", "washing-05", "process", "Wringing out the cloth"),
    (f"{W}/DSC00291.JPG", "washing-06", "process", "Rinsing lengths of cotton"),
    (f"{W}/DSC00294.JPG", "washing-07", "process", "The washing tank under the trees"),
    (f"{W}/DSC00295.JPG", "washing-08", "process", "Washing in running water"),
    (f"{W}/DSC00318.JPG", "dyeing-01", "process", "Lifting cloth from the dye vat"),
    (f"{W}/DSC00321.JPG", "dyeing-02", "process", "Working the dye into the cloth"),
    (f"{W}/DSC00322.JPG", "dyeing-03", "process", "Indigo-dyed cloth, just out of the vat"),
    (f"{W}/DSC00328.JPG", "dyeing-04", "process", "Preparing the dye bath"),
    (f"{W}/DSC00330.JPG", "dyeing-05", "process", "The dyer at the copper vat"),
    (f"{W}/DSC00333.JPG", "dyeing-06", "process", "Stirring the vat"),
    (f"{W}/DSC00334.JPG", "dyeing-07", "process", "Carrying dye to the vat"),
    (f"{W}/DSC00337.JPG", "dyeing-08", "process", "Dyeing in a copper cauldron"),
    (f"{W}/DSC00339.JPG", "dyeing-09", "process", "Madder red in the vat"),
    (f"{W}/DSC00344.JPG", "dyeing-10", "process", "Beside the indigo tank"),
    (f"{W}/DSC00354.JPG", "dyeing-11", "process", "Rinsing dyed cloth"),
    (f"{W}/DSC00357.JPG", "dyeing-12", "process", "Rinsing after the dye bath"),
    # ---------- Old catalogue (late 1990s) ----------
    (f"{H}/blockprint1 - bed.jpg", "cat-blockprint-bed", "catalogue", "Indigo block-printed bed linen and cushions, from our first catalogue"),
    (f"{H}/emb1 - cushion cover.jpg", "cat-embroidered-cushions", "catalogue", "Hand-embroidered cushion covers"),
    (f"{H}/mfgprocess-of-blockprint.jpg", "cat-process-blockprint", "catalogue", "Block printing, as photographed for our first catalogue"),
    (f"{H}/mfgprocess-of-blockprint2.jpg", "cat-process-drying", "catalogue", "Lengths of red cloth drying in the sun"),
    (f"{H}/mfgprocess-of-emb(1st&secondleftonly).jpg", "cat-process-embroidery-2", "catalogue", "Embroidery and tie-dye in progress"),
    (f"{H}/mfgprocess-of-embrodary.jpg", "cat-process-embroidery", "catalogue", "Two embroiderers at work"),
    (f"{H}/mfgprocess-of-weaving(kharal).jpg", "cat-process-weaving", "catalogue", "Weaving a dhurrie on the ground loom"),
    (f"{H}/patchwork2 - catelogue.jpg", "cat-patchwork-cushions", "catalogue", "Patchwork cushions in blue and green"),
    (f"{H}/patchwork3 - bedcover,cushioncover,curtain.jpg", "cat-patchwork-bed", "catalogue", "Patchwork bedcover, cushions and curtain"),
    (f"{H}/patchwork4 - wall hanging (figure).jpg", "cat-wallhanging", "catalogue", "Appliqué wall hanging with figures and animals"),
    (f"{H}/quilts1 - gujarat.jpg", "cat-quilts", "catalogue", "Rolled hand-quilted throws from Gujarat"),
    (f"{H}/tie&dye2 - wine.jpg", "cat-tiedye-wine", "catalogue", "Bandhani tie-dye in wine"),
    (f"{H}/tie&dye3 - scarves.jpg", "cat-tiedye-scarves", "catalogue", "A pile of tie-dyed scarves"),
    (f"{H}/weaving1 - cottondari.jpg", "cat-dhurrie", "catalogue", "Hand-woven cotton dhurrie"),
    # ---------- Archive: Kantha (Bengal) ----------
    (f"{C}/KANTHA/107_3038.JPG", "arch-kantha-01", "archive", "Kantha with lattice ground and central lotus, Bengal"),
    (f"{C}/KANTHA/107_3039.JPG", "arch-kantha-02", "archive", "Kantha lotus medallion, detail"),
    (f"{C}/KANTHA/107_3040.JPG", "arch-kantha-03", "archive", "Red-on-white floral kantha"),
    (f"{C}/KANTHA/107_3042.JPG", "arch-kantha-04", "archive", "Scattered-flower kantha"),
    (f"{C}/KANTHA/107_3043.JPG", "arch-kantha-05", "archive", "Lotus-and-vine kantha, detail"),
    (f"{C}/KANTHA/IMG_4718.JPG", "arch-kantha-06", "archive", "Fine running-stitch kantha with paisleys"),
    (f"{C}/KANTHA/IMG_4719.JPG", "arch-kantha-07", "archive", "Kantha paisley, detail"),
    (f"{C}/KANTHA/IMG_4724.JPG", "arch-kantha-08", "archive", "Kantha with radiating petals"),
    (f"{C}/KANTHA 1/107_3300.JPG", "arch-kantha-09", "archive", "Figurative nakshi kantha"),
    (f"{C}/KANTHA 1/107_3310.JPG", "arch-kantha-10", "archive", "Kantha with sun-wheel medallion and borders"),
    (f"{C}/KANTHA 1/107_3311.JPG", "arch-kantha-11", "archive", "Sun-wheel kantha, detail"),
    (f"{C}/KANTHA 1/107_3313.JPG", "arch-kantha-12", "archive", "Densely stitched kantha medallion"),
    (f"{C}/KANTHA 1/107_3316.JPG", "arch-kantha-13", "archive", "Kantha with paisleys and quatrefoils"),
    (f"{C}/KANTHA 1/107_3317.JPG", "arch-kantha-14", "archive", "Kantha quatrefoils, detail"),
    # ---------- Archive: Patchwork & applique (Gujarat / Rajasthan) ----------
    (f"{C}/PATCH WORK/107_1292.JPG", "arch-applique-01", "archive", "Appliqué canopy with sun-wheel, Saurashtra"),
    (f"{C}/PATCH WORK/107_1295.JPG", "arch-applique-02", "archive", "Appliqué canopy, detail"),
    (f"{C}/PATCH WORK/107_1296.JPG", "arch-applique-03", "archive", "Appliqué sun-wheel"),
    (f"{C}/PATCH WORK/107_1298.JPG", "arch-applique-04", "archive", "Appliqué toran with hanging flaps"),
    (f"{C}/PATCH WORK/107_1300.JPG", "arch-applique-05", "archive", "Appliqué medallion, detail"),
    (f"{C}/PATCH WORK/107_2689.JPG", "arch-applique-06", "archive", "Pieced quilt with chevron border"),
    (f"{C}/PATCH WORK/107_2690.JPG", "arch-applique-07", "archive", "Pieced quilt of triangles and squares"),
    (f"{C}/PATCH WORK/107_2873.JPG", "arch-applique-08", "archive", "Embroidered and pieced chakla"),
    (f"{C}/PATCH WORK/107_3143.JPG", "arch-applique-09", "archive", "Appliqué hanging with tree of life"),
    (f"{C}/PATCH WORK/107_3144.JPG", "arch-applique-10", "archive", "Appliqué flowers, detail"),
    (f"{C}/PATCH WORK/107_3145.JPG", "arch-applique-11", "archive", "Appliqué tree of life"),
    (f"{C}/PATCH WORK/107_3146.JPG", "arch-applique-12", "archive", "Appliqué elephants, detail"),
    (f"{C}/PATCH WORK/107_3149.JPG", "arch-applique-13", "archive", "Appliqué sun-wheel on red"),
    (f"{C}/PATCH WORK/107_3151.JPG", "arch-applique-14", "archive", "Appliqué door hanging with elephants"),
    (f"{C}/PATCH WORK/107_3154.JPG", "arch-applique-15", "archive", "Appliqué garment"),
    (f"{C}/PATCH WORK/107_3208.JPG", "arch-applique-16", "archive", "Embroidered hanging with elephants and riders"),
    (f"{C}/PATCH WORK/107_3223.JPG", "arch-applique-17", "archive", "Embroidered runner with animals"),
    (f"{C}/PATCH WORK/107_3225.JPG", "arch-applique-18", "archive", "Embroidered medallions and horses, detail"),
    # ---------- Archive: Tie-dye / bandhani ----------
    (f"{C}/TIE DYE/107_3079.JPG", "arch-bandhani-01", "archive", "Embroidered garment on red"),
    (f"{C}/TIE DYE/107_3085.JPG", "arch-bandhani-02", "archive", "Fine bandhani in madder and black"),
    (f"{C}/TIE DYE/107_3086.JPG", "arch-bandhani-03", "archive", "Bandhani odhani"),
    (f"{C}/ekat & KE shawl/DSC04086.JPG", "arch-bandhani-04", "archive", "Bandhani with yellow and green dots"),
    (f"{C}/ekat & KE shawl/DSC04087.JPG", "arch-bandhani-05", "archive", "Bandhani, detail"),
    (f"{C}/ekat & KE shawl/DSC04089.JPG", "arch-bandhani-06", "archive", "Large-motif bandhani"),
    # ---------- Archive: Kashmir shawls ----------
    (f"{C}/kashmir shawl/100_0042.JPG", "arch-kashmir-01", "archive", "Kashmir moon shawl"),
    (f"{C}/kashmir shawl/100_0045.JPG", "arch-kashmir-02", "archive", "Kashmir long shawl with paisleys"),
    (f"{C}/kashmir shawl/100_0048.JPG", "arch-kashmir-03", "archive", "Kashmir shawl, centre detail"),
    (f"{C}/kashmir shawl/107_2099.JPG", "arch-kashmir-04", "archive", "Embroidered Kashmir shawl"),
    (f"{C}/kashmir shawl/107_2100.JPG", "arch-kashmir-05", "archive", "Kashmir shawl, corner"),
    (f"{C}/kashmir shawl/107_2815.JPG", "arch-kashmir-06", "archive", "Paisley shawl in blue and cream"),
    (f"{C}/kashmir shawl/107_2817.JPG", "arch-kashmir-07", "archive", "Paisley shawl, detail"),
    (f"{C}/kashmir shawl/107_2818.JPG", "arch-kashmir-08", "archive", "Paisley shawl border"),
    (f"{C}/kashmir shawl/107_2820.JPG", "arch-kashmir-09", "archive", "Woven paisley shawl"),
    (f"{C}/kashmir shawl/IMG_4247.JPG", "arch-kashmir-10", "archive", "Shawl border with floral vine"),
    # ---------- Archive: Mochi / Kalamkari / Brocade / Zari ----------
    (f"{C}/mochi embroidery/107_2674.JPG", "arch-mochi-01", "archive", "Mochi embroidered hanging, Kutch"),
    (f"{C}/mochi embroidery/107_2675.JPG", "arch-mochi-02", "archive", "Mochi embroidery, figures in medallion"),
    (f"{C}/mochi embroidery/107_2676.JPG", "arch-mochi-03", "archive", "Mochi embroidery with animals"),
    (f"{C}/mochi embroidery/107_2680.JPG", "arch-mochi-04", "archive", "Mochi embroidery, detail"),
    (f"{C}/mochiskirt/MOCHI_SKIRT1.jpg", "arch-mochi-skirt", "archive", "Red silk skirt with mochi embroidery"),
    (f"{C}/mochiskirt/MOCHI_SKIRT2.jpg", "arch-mochi-skirt-2", "archive", "Mochi embroidered skirt, detail"),
    (f"{C}/kamalkari south/107_2065.JPG", "arch-kalamkari-01", "archive", "Embroidered floral square"),
    (f"{C}/kamalkari south/107_2066.JPG", "arch-kalamkari-02", "archive", "Embroidered shawl with fringe"),
    (f"{C}/kamalkari south/107_2068.JPG", "arch-kalamkari-03", "archive", "Kalamkari hanging, South India"),
    (f"{C}/kamalkari south/107_2069.JPG", "arch-kalamkari-04", "archive", "Kalamkari hanging with figures"),
    (f"{C}/kamalkari south/107_2071.JPG", "arch-kalamkari-05", "archive", "Kalamkari panel"),
    (f"{C}/kamalkari south/107_2073.JPG", "arch-kalamkari-06", "archive", "Kalamkari, painted figures"),
    (f"{C}/kamalkari south/107_2076.JPG", "arch-kalamkari-07", "archive", "Kalamkari narrative panel"),
    (f"{C}/New Folder (2)/IMG_0014.jpg", "arch-brocade-01", "archive", "Purple and silver brocade"),
    (f"{C}/New Folder (2)/IMG_0017.jpg", "arch-brocade-02", "archive", "Red and gold brocade"),
    (f"{C}/New Folder (2)/IMG_0019.jpg", "arch-brocade-03", "archive", "Gold brocade with red border"),
    (f"{C}/New Folder (2)/IMG_0021.jpg", "arch-brocade-04", "archive", "Gold brocade"),
    (f"{C}/New Folder (2)/IMG_0022.jpg", "arch-brocade-05", "archive", "Red and gold brocade, detail"),
    (f"{C}/New Folder (2)/IMG_0025.jpg", "arch-brocade-06", "archive", "Purple brocade with animals"),
    (f"{C}/zari/107_2846.JPG", "arch-zari-01", "archive", "Zari embroidered panel"),
    # ---------- Archive: Patola & ikat ----------
    (f"{C}/ekat & KE shawl/DSC03810.JPG", "arch-patola-01", "archive", "Patola double-ikat, Patan"),
    (f"{C}/ekat & KE shawl/DSC03813.JPG", "arch-patola-02", "archive", "Framed patola in the weaver's home"),
    (f"{C}/ekat & KE shawl/DSC03816.JPG", "arch-patola-03", "archive", "Patola, detail"),
    (f"{C}/ekat & KE shawl/DSC03818.JPG", "arch-patola-04", "archive", "A patola weaver presents a sari"),
    (f"{C}/ekat & KE shawl/DSC03819.JPG", "arch-patola-05", "archive", "Patola star-lattice, detail"),
    (f"{C}/ekat & KE shawl/DSC03825.JPG", "arch-patola-06", "archive", "Elephant patola"),
    (f"{C}/ekat & KE shawl/DSC03827.JPG", "arch-patola-07", "archive", "Elephant patola, full length"),
    (f"{C}/ekat & KE shawl/DSC03829.JPG", "arch-patola-08", "archive", "Elephant patola, detail"),
    (f"{C}/ekat & KE shawl/DSC03830.JPG", "arch-patola-09", "archive", "Patola with tigers and elephants"),
    (f"{C}/ekat & KE shawl/DSC03836.JPG", "arch-patola-10", "archive", "The weaver and his patola"),
    (f"{C}/ekat & KE shawl/DSC03838.JPG", "arch-patola-11", "archive", "Patola, detail"),
    (f"{C}/ekat & KE shawl/DSC03843.JPG", "arch-patola-12", "archive", "Patola with dancing figures"),
    (f"{C}/ekat & KE shawl/DSC03845.JPG", "arch-patola-13", "archive", "Patola parrot motif"),
    (f"{C}/ekat & KE shawl/DSC03811.JPG", "arch-patola-loom", "archive", "The patola loom"),
    (f"{C}/ekat & KE shawl/DSC03873.JPG", "arch-patola-14", "archive", "Patola flower lattice"),
    (f"{C}/ekat & KE shawl/DSC03874.JPG", "arch-patola-15", "archive", "Patola with elaborate borders"),
    (f"{C}/ekat & KE shawl/DSC03879.JPG", "arch-patola-16", "archive", "Patola with cream field"),
    (f"{C}/ekat & KE shawl/DSC04065.JPG", "arch-shawl-01", "archive", "Embroidered shawl with medallion"),
    (f"{C}/ekat & KE shawl/DSC04067.JPG", "arch-shawl-02", "archive", "Kashmir shawl, paisley detail"),
    (f"{C}/ekat & KE shawl/DSC04071.JPG", "arch-painted-01", "archive", "Painted narrative cloth"),
    (f"{C}/ekat & KE shawl/DSC04077.JPG", "arch-ikat-01", "archive", "Ikat with painted border"),
    (f"{C}/ekat & KE shawl/DSC04083.JPG", "arch-embroidered-border", "archive", "Embroidered border with metallic thread"),
    (f"{C}/ekat & KE shawl/DSC04095.JPG", "arch-patola-17", "archive", "Patola star motif"),
    (f"{C}/ekat & KE shawl/DSC04097.JPG", "arch-patola-18", "archive", "Patola with lattice and flowers"),
    (f"{C}/ekat & KE shawl/DSC04102.JPG", "arch-mirror-01", "archive", "Mirror-work embroidery, Kutch"),
    (f"{C}/ekat & KE shawl/DSC04104.JPG", "arch-mirror-02", "archive", "Mirror-work embroidery, detail"),
]
